### ISSUE TITLE
TouchSwipe ignores allowPageScroll option and prevents all scrolling in iOS Safari

### ISSUE THREAD

**Issue by nathanbatson** [mattbryson/TouchSwipe-Jquery-Plugin#260]
### JSBin of the issue:
http://jsbin.com/peyeci/

I may come back and create a PR to fix this issue, however I just wanted to log this incase anyone else is searching for a resolution to this.

### Workaround 
Downgrade to `1.6.9` or `1.6.10`

**Comment by mkamla** [comment]
Can confirm @nathanbatson's finding. However I've noticed that scrolling will work on the element if finger is initially started on a child anchor tag. Perhaps due to event propagation?

Will review 1.6.9 and 1.6.10, as recommended by Nathan.

**Comment by daggerjames** [comment]
I met similar question, so basically this is what I found.

When I try to let the vertical scrolling work as default, while define the swipeLeft and swipeRight event, the first calculateDirection would consider separate startPoint and endPoint AT THE START POINT, as you might see the printed result. It means, if we print out the direction, it would be like UP,UP,UP... (for a swipeUp gesture).
![image](https://cloud.githubusercontent.com/assets/15273039/10708394/8d6fe50a-7a39-11e5-8313-eec07dcf11c5.png)
(in Chrome)

However, same page on my iPhone, it seems that at the first time, the startPoint and endPoint is SAME.(I believe that iPhone fires quick 0.0) Then the program would calculate the angel as 0, which means, the direction would be LEFT, UP,UP, UP .... (for a swipeUp gesture too). Since I have defined a swipeleft function, you know the preventDefault() would be executed (Even I don't want).
![iphone](https://cloud.githubusercontent.com/assets/15273039/10708438/e5fe9d96-7a3a-11e5-8da3-19756bdca072.jpg)
(My iPhone)

I just simply change the touchSwipe code like 
![image](https://cloud.githubusercontent.com/assets/15273039/10708416/6c2c7cea-7a3a-11e5-9203-b1c539a82401.png)
to fix it, but I believe that you guys would consider it more strictly, lol

**Comment by okwei2000** [comment]
Having the same issue, have to revert back..

**Comment by marcinkrzeminski** [comment]
Hi,

I'm having this issue in 1.6.12. Should I downgrade to 1.6.9 as well?

**Comment by mattbryson** [comment]
Fixed in 1.6.13

**Comment by syropian** [comment]
I'm using the latest version (`1.6.15`), and still have this issue. Anyone else?

**Comment by tletie** [comment]
Yes, I have the same issue with 1.6.13 or 1.6.1. it ignore allowPageScroll

**Comment by tletie** [comment]
A workaround is instead of using allowPageScroll: "auto" or "vertical", if you use "horizontal" then it will work on a real device (iOS-Safari) not on Chrome - ios mobile simulator.

**Comment by skyprod** [comment]
I have the same problem with the latest version, downloaded today. No error messages, just ignores allowPageScroll: 'vertical', like it wasn't there. Amazing plugin anyways! Thanks

**Comment by FriOne** [comment]
I guess the problem is described [here](http://stackoverflow.com/a/7965604/2918518)

**Comment by viniciusnz** [comment]
+1 @daggerjames for the great answer... it worked instantly on my iphone... Thanks!

**Comment by michaelbrawn** [comment]
I can also confirm @daggerjames fix works for Safari on iOS 9.3.1 and TouchSwipe 1.6.15

**Comment by BoByBrno** [comment]
@daggerjames THX your fix work for me

**Comment by mattbryson** [comment]
Ill have a look at sorting this, thanks for the fix @daggerjames

**Comment by magglomag** [comment]
I still have this issue even when adding @daggerjames’ solution.
Any suggestions?

**Comment by EnzoIntiso** [comment]
> Not to sure how that helps. If pageScroll is 'auto' (the default) then assigning a swipeLeft handler will capture ONLY swipe left events. All other swipes events will propagate up and trigger a native page scroll.

It's still buggy on iOS 9.3.2 as, even if with pagescroll 'auto' and only swipeLeft and swipeRight assigned, vertical scrolling is faulty (sometimes works sometimes not). It seems that swipeUp and swipeDown are caught anyway even if don't assigned preventing scrolling.
